### ISSUE TITLE
App crash if you try access a project of type Talent

### ISSUE THREAD

**Issue by skaue** [Microsoft/2LCS#1]
If you try open a project of type Talent, the app crashes. 

(Norwegian) Callstack:
System.Net.Http.HttpRequestException: Svarstatuskoder indikerer ikke at forespørselen var vellykket: 403 (Forbidden).
   ved System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   ved LCS.HttpClientHelper.GetCheInstances() i C:\Users\tmelissa\Source\repos\2LCS\2LCS\HttpClientHelper.cs:linje 84
   ved LCS.Forms.MainForm.RefreshChe(Boolean reloadFromLcs) i C:\Users\tmelissa\Source\repos\2LCS\2LCS\Forms\MainForm.cs:linje 211
   ved LCS.Forms.MainForm.RefreshMenuItem_Click(Object sender, EventArgs e) i C:\Users\tmelissa\Source\repos\2LCS\2LCS\Forms\MainForm.cs:linje 167
   ved System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   ved System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   ved System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   ved System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   ved System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   ved System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   ved System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   ved System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   ved System.Windows.Forms.Control.WndProc(Message& m)
   ved System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   ved System.Windows.Forms.ToolStrip.WndProc(Message& m)
   ved System.Windows.Forms.MenuStrip.WndProc(Message& m)
   ved System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   ved System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Splaxi** [comment]
@skaue I would say that the error indicates that your credentials that you used to sign in, didn't have enough permissions / privileges. Error 403 normally indicates that the server refused for some reason.

I have created a fork that should "silently" survive the issue.

Have a look here:
https://github.com/Splaxi/2LCS

If you want, you could set a breakpoint a line 85 in the HttpClientHelper class. Give result.Content, result.Headers & result.ReasonPhrase a closer look. Put them in your Watch window or use the Immediate Window to see what they contain.

Give it a swing :)
