### ISSUE TITLE
AADSTS90004: Incoming message is malformed. 

### ISSUE THREAD

**Issue by veercv** [Microsoft/2LCS#10]
Getting this message when login using organizational account: AADSTS90004: Incoming message is malformed.

**Comment by neveskiet** [comment]
Is there anyone who knows to fix this issue? I'm facing the exact same issue.

**Comment by torbennehmer** [comment]
Best guess: I have similar problems some times when the authentication is mangled up. Try to log out and relog in, this often fixes various problems with 2LCS. Be aware, that you've to reflag your favorites at that point, unfortunately.

**Comment by PaulHeisterkamp** [comment]
I also still have this problem...

**Comment by lampekappie** [comment]
It seems I only have this issue when connecting OnPrem through ADFS. Connecting with the same device remotely, it does connect.

**Comment by PaulHeisterkamp** [comment]
The problem is fixed! Thanks Tomek!
