### ISSUE TITLE
Build number (exact application version)

### ISSUE THREAD

**Issue by DiSae** [Microsoft/2LCS#17]
Hello,

The below is an idea, not an issue.

Currently there's a column named 'Current Application Release Name' which shows the Application version displayed on the Environment overview page in LCS.
In some cases, this will show 8.1 while the exact application version is actually 8.1.1 or 8.1.2 ...

Would it be possible to add a column for the 'Exact Application Build Number'?

A procedure to verify this number manually can be found below:
![image](https://user-images.githubusercontent.com/31828724/50960789-76c1c000-14c6-11e9-9e9c-d059f213a538.png)

**Comment by TomekMelissa** [comment]
This information is not included in LCS response with instance details. It is only available on "Detailed version information" page https://diag.lcs.dynamics.com/BuildInfo/Index/{LCSProjectId}?lcsEnvironmentId={EnvironmentId}

I could fetch info about AppSuite version number from here to include it on the grid, but it would impact the speed of 2LCS instance refresh quite heavily. Instead I will implement this detailed version view in table form like with the hotfixes, so you will be able to see it easily on demand. 
What do you think?

**Comment by TomekMelissa** [comment]
Implemented

**Comment by MarcelGoossens** [comment]
Hi Tomek,

Is the version linked to  ElektronicReporting (Under Publisher name - Microsoft Corporation) not the correct reference to the exact build ? When deploying a clean, new 8.1.3 environment the only versionnumber giving 8.1.3(0180.3) is Elektronic reporting, AppSuite and other are then 8.1.227.xxxx.
Or am I missing something ?

Regards, Marcel

**Comment by TomekMelissa** [comment]
IMO there is no such thing as exact application build number. Only major release number and lots of build numbers of different modules. Following those ever changing naming and numbering conventions is hard... :)
