### ISSUE TITLE
Icon on task bar

### ISSUE THREAD

**Issue by DiSae** [Microsoft/2LCS#18]
Hello,

Would it be possible to have an icon on the task bar for this application please?
After minimizing the app, you need to search for it to reopen it. An icon on the task bar would make it much more user friendly.

Currently you have to either click on the arrow on the task bar to reopen the app 
![image](https://user-images.githubusercontent.com/31828724/51303311-48e3fa80-1a35-11e9-8f5b-7ef220c86da9.png)
or minimize other open windows to find the below again:
![image](https://user-images.githubusercontent.com/31828724/51303348-5ef1bb00-1a35-11e9-9ff5-3321a7bde188.png)

Thank you.

**Comment by TomekMelissa** [comment]
I would like to keep it in systray. You can decide which icon should be always visible. This way you can keep it available with single click all time.
![image](https://user-images.githubusercontent.com/3280745/51303613-2c948d80-1a36-11e9-8a7c-caf8f4ae2397.png)
