### ISSUE TITLE
RDP details Saas not availiable anymore ?

### ISSUE THREAD

**Issue by MarcelGoossens** [Microsoft/2LCS#19]
Is there a change in LCS and the Saas RDP details are not avaliable anymore in 2LCS?

**Comment by TomekMelissa** [comment]
Soon it will not be available completely. For now check if you enabled remote access. Go to Maintain\Enable Access

**Comment by MarcelGoossens** [comment]
I have access, my IP is specified in the firewall (s), but via 2LCS the form is now empty (previously this was  available to me)

**Comment by TomekMelissa** [comment]
I will have a look...

**Comment by Splaxi** [comment]
I'm seeing the same thing @TomekMelissa 

Debugging is showing me that the LCS thinks I don't have access. I guess someone changed something at LCS with the latest release.

```
Please enable access to your environment before continuing. Select "Maintain -> Enable Access" to specify your IP address space. Starting October 1st 2017, you will no longer be able to connect to this environment, unless you have specified access rules to your environment.
```

**Comment by Splaxi** [comment]
I dug around a bit more.

When I first visit my build environment page on LCS, i get this error if I try to download the RDP file - but only the first time.

![image](https://user-images.githubusercontent.com/8750181/53202874-e8de0680-3627-11e9-9327-f9c9cf16aaf5.png)

If I do it again as quickly as possible, it doesn't show the same error again and the RDP file is downloaded as expected.

I would say someone at MS and their LCS team should have a look at it.

**Comment by MarcelGoossens** [comment]
Hi Tomec,

Did you already had a chance to take a look at this? Show RDP details environment gives a empty form.

Regards, Marcel

![rdpdetails](https://user-images.githubusercontent.com/16332956/53397221-dc023f80-39a6-11e9-8dbf-59c027ef9c53.png)

**Comment by MarcelGoossens** [comment]
:-) Super, thnx
