### ISSUE TITLE
Logon issue

### ISSUE THREAD

**Issue by MZade** [Microsoft/2LCS#22]
Hi, I'm getting the following error message during the logon to LCS from the 2LCS application.
Is there anything that I can do about this ?

p.s. normally the account I'm using has Project admin access on some LCS projects.

![image](https://user-images.githubusercontent.com/19854220/53917827-c1465f80-4065-11e9-9098-c96e5cea2ade.png)

**Comment by TomekMelissa** [comment]
This is fixed since 0.9.2. Please use latest version.
