### ISSUE TITLE
QUESTION: LOADED PACKAGES AND THEIR MODELS

### ISSUE THREAD

**Issue by MZade** [Microsoft/2LCS#23]
Hi, Is it somehow technically achieveable to extend the 2LCS application and extract the information related to "LOADED PACKAGES AND THEIR MODELS" which is normally visible under the "About" dialog from the application ?

![image](https://user-images.githubusercontent.com/19854220/53939900-9fc09480-40b4-11e9-8b6b-d16e7442c0b8.png)

**Comment by TomekMelissa** [comment]
Doesn't "Detailed Build Info" option give you enough information?

**Comment by MZade** [comment]
Hi @TomekMelissa , 

Do you mean the "Build Info" column in the following screenshot (see bellow)?
In that case, I would say this would not be enough.

We are looking for a way to collect which version of ISV or own VAR modules as well as well as MS modules are used on every project to be able to anticipate on each project from a central point.

It would be great to have the "Component details" listing that is visible under the "Software deployable package asset library" for the deployable package that is installed on the given environment as extended report per environment. This would be very usefull to have for T2+ environments.

![image](https://user-images.githubusercontent.com/19854220/54046484-caa20a00-41d4-11e9-9080-c4014542674b.png)

![image](https://user-images.githubusercontent.com/19854220/54046661-51ef7d80-41d5-11e9-95c8-6b810755c0f2.png)

**Comment by MZade** [comment]
Thanks. This is helping a lot:

![image](https://user-images.githubusercontent.com/19854220/54047349-2372a200-41d7-11e9-90f4-3831d9fad54c.png)
