### ISSUE TITLE
Project User Management data for 2LCS

### ISSUE THREAD

**Issue by MarcelGoossens** [microsoft/2LCS#27]
Hi Tomek,

Not an issue but more a question ... 
Is it possible to easily obtain the data from the LCS Project User Management page (Name, Organization, Projectrole) via 2LCS in a form or export-function ?

Regards, Marcel

**Comment by TomekMelissa** [comment]
Sure it can be done. I will implement it in next version ;)

**Comment by MarcelGoossens** [comment]
Thnx!  :-)

**Comment by MarcelGoossens** [comment]
Hi Tomek,

Small bug which I am experiencing ? .. 
if a user has the status 'Pending' in the LCS Project User Management, 2LCS will stop due to ProjectUser.UserProfile.get returned null.

Regards, Marcel
