### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Sigvelli** [microsoft/2LCS#29]
Are there any 2LCS documentation other than README.md? 
How could the menu "Define custom links" and "Cookie" be used?

**Comment by TomekMelissa** [comment]
"Define custom links" is a feature where you can add additional menu items (links) into 2LCS instance context menu. Using placeholders you can "build" such URLs to access additional LCS or instance pages. 
"Cookie" allows you to copy or paste cookie used to access LCS. This way you can in example temporarily share access to LCS without giving credentials. It was introduced only as a workaround for some logon problems people experienced when using accounts behind some proxy etc. It should not be used in normal circumstances.
