### ISSUE TITLE
Deploy Package no longer working

### ISSUE THREAD

**Issue by caleblanchard** [microsoft/2LCS#30]
I used to use the deploy package feature quite a bit, It made it simple to deploy a version update to many different environments much quicker that through LCS. However, recently, this feature stopped working. It appears it might be something on the LCS side. I am wondering if the "API" in LCS changed so that the deploy package no longer works.

**Comment by TomekMelissa** [comment]
Could you provide more details? Are you able to choose package? What is displayed in deploy log window? what is your LCS project type?
I just tried that in my learning project and deployment of a package started successfully.

**Comment by caleblanchard** [comment]
It seems like it might be related to version update packages. Maybe it is PU update specific. It seems I can deploy custom packages or non PU related packages. Here is the error when I try to deploy 10.0.4 PU28 to a 10.0.0 PU25 environment via 2LCS: 
![image](https://user-images.githubusercontent.com/23510045/63025612-944d7280-be77-11e9-8c08-a035eb46f422.png)

**Comment by caleblanchard** [comment]
May I ask why this has been closed? I am not able to deploy PU update packages still. I used to be able to do that.

**Comment by TomekMelissa** [comment]
version 0.20.0 is the answer.

**Comment by caleblanchard** [comment]
Ah. Sorry. Still a little new to Github. I see now that it is closed with a specific commit. Thank you!

**Comment by TomekMelissa** [comment]
Please download version 0.20.0 again. binaries inside were still faulty.
