### ISSUE TITLE
Question: Upcoming Updates LCS

### ISSUE THREAD

**Issue by MarcelGoossens** [microsoft/2LCS#36]
Hi Tomek,

Just a free question, and whether this is possible to make available in your nice tool.
The data from the upcoming updates for the sandbox environments in lcs to a form or export?
Under the project settings - Update Settings - Edit settings.

Attachted a screenshot.

Regards, Marcel
![updatesettings](https://user-images.githubusercontent.com/16332956/67520859-f31a3e00-f6a9-11e9-98bd-f93754833267.png)

**Comment by TomekMelissa** [comment]
check release 0.24.0 and close this issue if it addresses your request.

**Comment by MarcelGoossens** [comment]
Super!  Thnx :-)
