### ISSUE TITLE
New Sandbox environments not shown in 2lcs

### ISSUE THREAD

**Issue by egfllau** [microsoft/2LCS#37]

**Comment by egfllau** [comment]
Hi. I have a customer where Microsoft sandbox environment is deployed as these new self-service environment. This environment does not show up in 2LCS. All Customer environment are present.

**Comment by egfllau** [comment]
Closed by mistake

**Comment by TomekMelissa** [comment]
I do not have access to self-service environments, so i cannot peek into LCS's responses. Would you care to save fiddler session for me?

**Comment by egfllau** [comment]
Hi Melissa.

Got this from Fiddler. Hope that helps.

Please provide setup settings if fiddler did not provide the info needed.


Venlig hilsen / best regards

Flemming Lauest
Systems Specialist
DXC Eclipse, Northern Europe

D: +45 7260 1435

M: +45 2066 5344
Fra: Tomek Melissa <notifications@github.com>
Sendt: 6. november 2019 14:12
Til: microsoft/2LCS <2LCS@noreply.github.com>
Cc: Flemming Lauest <fllau@eg.dk>; State change <state_change@noreply.github.com>
Emne: Re: [microsoft/2LCS] New Sandbox environments not shown in 2lcs (#37)


I do not have access to self-service environments, so i cannot peek into LCS's responses. Would you care to save fiddler session for me?

**Comment by TomekMelissa** [comment]
Implemented in v.0.26.0
