### ISSUE TITLE
Define custom links

### ISSUE THREAD

**Issue by kjgro** [microsoft/2LCS#38]
Hi! 
I have a wish for "define custom links":
Is it possible to add the application base url as a variable ? Then we would be able to create custom links as : https://%%applicationbaseurl%%/?mi=ProjProjectsListPage to open that page directly.

**Comment by TomekMelissa** [comment]
I like this. Should be there from the beginning... V25 implements this.

**Comment by kjgro** [comment]
Nice, now this gem of a tool becomes even more useful! Thanks!
