### ISSUE TITLE
Environment Changes

### ISSUE THREAD

**Issue by MarcelGoossens** [microsoft/2LCS#39]
Question/Request.

Is it possible to get the records from the environment historie in LCS?
(Environment Details - History - Environment changes)
With this you would have a faster overview from failed/incorrect deployments and database restore actions. Does not have to be all records  but for example the last 10 (most recent) records from the LCS form.

Regards, Marcel

**Comment by TomekMelissa** [comment]
Everything is possible :), but in this case you do have a direct link in instance context menu to the page with all those details. Is it really worth implementing it in the app? Convince me.

**Comment by MarcelGoossens** [comment]
:-)
Convince you, hahaha.. ok, the mentioned portal link is avaliable as a 'link' which means another prog has to open it and often requires a 'number' of account login's. It would be faster when this data is avaliable direct in 2LCS ? 
No problem if you find this not really necessary but as indicated, just a question (and it is possible as I read  :-)   )

**Comment by MarcelGoossens** [comment]
Oeps, forgotten to say. We notice that due to the ever increasing number of updates/environments (including customizations) and associated bugs and other issues, the course of these environments changes are quite important to know...

Regards, Marcel

**Comment by nb-tergen** [comment]
I'd argue that everything which is not available in an API is worth implementing here, as LCS UX is not sufficient when working across numerous projects, and for me the features in 2LCS which I have contributed to thus far are those which allow the export of information across projects such that we can get a birds eye view.

**Comment by MarcelGoossens** [comment]
Maybe a good intention for 2020? ;-)  But first of course the best wishes!

**Comment by TomekMelissa** [comment]
Ok. So if I will display the list of historic actions available in the grid this will fulfill your needs, right?

**Comment by MarcelGoossens** [comment]
That sure will fulfill a lot!  Thnx  ;-)

**Comment by TomekMelissa** [comment]
See 0.27.0 and let me know your thoughts.

**Comment by MarcelGoossens** [comment]
Hi Tomek,
Looks good and is the overview needed / I asked for  ;-)
Thnx for this addition!

I'll also close this request.
