### ISSUE TITLE
Log into 2LCS with a different account

### ISSUE THREAD

**Issue by Sigvelli** [microsoft/2LCS#40]
I have two different accounts that I use in Lifecycle Services. Are there any workaround for logging into 2LCS with different accounts? I am only able to log in with the same account that my laptop currently are using.

**Comment by MarcelGoossens** [comment]
Check the adding from Tomek:
Added ability to paste cookie instead of logging in. 
TomekMelissa committed on 19 Apr… single sing-on scenarios when you need to use other account.

[https://github.com/microsoft/2LCS/commit/70440e734713809c9faec9a26c70817716ae61e4](url)

**Comment by Sigvelli** [comment]
I am sorry, but I do not quite see how I can use cookies to change accunt. Do you have an example?

**Comment by TomekMelissa** [comment]
You need to completely logout from your account in Internet Explorer. Close all its working windows to make sure no session was left open. Then open 2LCS and it should prompt you for credentials. 
In cookie window you can see and copy cookie for later use if you do not want to repeat the login process every time you need to switch accounts in 2LCS. 
Be aware that cookies expire and you will need to repeat that anyway, but maybe not so often.
To use saved cookie just open cookie form and paste it there. Then the application will behave as you logged in for the first time.

**Comment by Sigvelli** [comment]
I logged out of both Edge, Firefox and Chrome, and it did not help. Then I noticed you wrote "logout from your account in Internet Explorer". To make it work I had to delete browsing history and saved passwords from Internet Explorer. Then I were able to change account in 2LCS. Problem solved! Thanks.
