### ISSUE TITLE
Release #26

### ISSUE THREAD

**Issue by Sigvelli** [microsoft/2LCS#42]
Thanks for the improvements in release 26. I have two comments.

In two out of my three Self service project the Build machine is missing from the "MS-hosted environments".
From those two LCS projects where a machine is missing, I notice that information in 2LCS is empty in the fiels of "Deployment action", Current application build version", "Current platform version","Build info" and the three Topology Name, Type and Version fields.

The order of instanced listed in MS-hosted environments seems to be random. I would prefer to have Production on top, as presented in LCS.
The order of cloud-hosted environments are identical to the order in LCS. Good!

**Comment by TomekMelissa** [comment]
Thank you for feedback.
I do not have access to any LCS project with self-service instances, so my implementation is kind of hit or miss. As I wrote in comments, problems are rather expected.
The order of instances in both cases is alphabetical on instance Id. I will have a look if I can easily sort it in the same way as in LCS. Definetely i can color-code different types of instances to make them easily identifiable.

**Comment by Sigvelli** [comment]
So if I gave you access to one of my Self-service LCS project you could fix this?

**Comment by TomekMelissa** [comment]
contact me tmelissa at microsoft.com
