### ISSUE TITLE
Version 27 & 28 are unstable 

### ISSUE THREAD

**Issue by Sigvelli** [microsoft/2LCS#49]
I am sorry to say, but on my laptop the new 2LCS versions are unstable. 

In version 27 & 28 the program will close without any error message if I press the "Refresh list" button from the "Choose LCS project" form.
The program will also close if I change project.
(Auto refresh is deactivated)

Version 26 is working ok for me.

**Comment by kjgro** [comment]
Try logout and then log in again

**Comment by Sigvelli** [comment]
Thanks for your suggestion. Logging out and then in again solves the problem, at least for a while. After a while (after a PC restart) the program starts to crash/stop again. Then I have to log out and in again to make it stop. I am not 100% satisfied with this workaround. I'll go for version #26.

**Comment by aariste** [comment]
Version 0.26.0 should also have this issue. The problem comes from the LCS cookie session expiry time that has been changed to 1 hour.

**Comment by TomekMelissa** [comment]
Have a look at 0.29.0
Thank you @aariste for PR with a quick fix.

**Comment by kjgro** [comment]
Nice, makes the cookie expiry time issue much less annoying. Thank you!

**Comment by Sigvelli** [comment]
Sorry, I am not 100% satisfied with version 0.29.0. Still the program stops on my laptop.

**Comment by TomekMelissa** [comment]
Well it is some corner case then, as I cannot repro your experience.
Could you share your cookie with me? Copy the content from Cookie form just after you successfully logged in. That would mean that I will get access to your projects for the duration of the cookie. 
If you agree please send it to me at tmelissa@microsoft.com

**Comment by egfllau** [comment]
I have same issues as Sigvelli starting from version 27 and still in 29. As soon as I change to another project and sometimes when change to another environment with same project.
