### ISSUE TITLE
Status on done fetching environments

### ISSUE THREAD

**Issue by Splaxi** [Microsoft/2LCS#5]
I think it would be of some help for the user, if we could give some sort of notification in the form, when we where done with fetching data about the different environments.

It could be:

- a popup
- a small note on the status bar (maybe with color)
- a running icon in the lower part of the form

Let me know what you think and I might be able to put in some time on that.

**Comment by TomekMelissa** [comment]
Good idea. I think something non-intrusive would be the best. I like the third option followed by status bar note.

**Comment by Splaxi** [comment]
I did something in the PR i just created.

I used the notify icon you already had in place. Give it a spin and let me know what you think :)
