### ISSUE TITLE
change LCS login

### ISSUE THREAD

**Issue by andraet** [microsoft/2LCS#53]
Am I the only person with more than one LCS account? When I started 2LCS the first time, it logged on to LCS with the "wrong" account and I dont find any way, to change that. What did I miss?
Thank you in advance!

**Comment by TomekMelissa** [comment]
If after logout in 2LCS you are presented with LCS logon screen and it automatically logs you in again it means you do have an active session in Internet Explorer. Open Internet Explorer and logout from your "wrong account". Close all IE windows and try again in 2LCS.

**Comment by andraet** [comment]
Thank you for the fast response - it worked perfectly!
