### ISSUE TITLE
Data region

### ISSUE THREAD

**Issue by Sigvelli** [microsoft/2LCS#60]
There is an issue in LCS for Self-service environments. The data region is from now on kept as a secret. For "Microsoft Managed" environments you still can see the information. Example: Primary region (Active) West Europe
So one cannot be sure in which data center your Self-Service environment  are located. This would be an very interesting information to present in 2LCS.

**Comment by TomekMelissa** [comment]
Unfortunately, this is no longer exposed in LCS app internal requests. Nothing I can do in 2LCS.
