### ISSUE TITLE
Region support 

### ISSUE THREAD

**Issue by flauest** [microsoft/2LCS#70]
Hi,
I use 2LCS a lot, but now we are getting LCS project that are from the new regions in LCS such as Europe and Norway.
Any way that 2LCS can support projects from other that then United States?
/Flemming

**Comment by FH-Inway** [comment]
The lcs.dynamics.com url is currently hard coded in a couple of files, see https://github.com/search?q=repo%3Amicrosoft%2F2LCS%20lcs.dynamics.com&type=code

A solution would at least require to make that configurable and expose that configuration somewhere in the ui. Not sure if further changes would be required.

**Comment by tfa-dk** [comment]
A quick search and replace of lcs.dynamics.com to eu.lcs.dynamics.com works.
I can start an environment, login to rdp and application. But the 2 2lsc.exes share a data cache, so you have to do a logout and login to see the right environments.

/Torben

**Comment by FH-Inway** [comment]
I played around with this and added some basic support for different regions in the parameters of 2LCS.
Note that after changing the urls, you need to log out and log in again.

If you want to test this version, you can go to [release 0.31.0](https://github.com/FH-Inway/2LCS/releases/tag/v.0.31.0) in my fork and download a compiled version there (or just compile the pull request version yourself).

Unfortunately I currently do not have access to LCS projects that are not in the US/global region, so I can't test it fully myself.

![image](https://user-images.githubusercontent.com/33372796/226124380-a5e9fbeb-deeb-46a8-8ff1-4507d383b504.png)

**Comment by flauest** [comment]
When using these parameters 
![image](https://user-images.githubusercontent.com/73821139/226284384-8673e9e8-6884-45a2-9def-0b3cb68baf10.png)
I get an logon error:
![image](https://user-images.githubusercontent.com/73821139/226284456-50b66c86-cb5e-46ec-8dfb-34749a6d8ddf.png)

Thx for doing the development. I would like a picking list for Geo, as I will be going to work in both US and EU every day.

**Comment by FH-Inway** [comment]
@flauest Thanks for testing!

For the LCS Diagnostic Url, your screenshot shows 2 dots after eu: 
```
https://diag.eu..lca.dynamics.com
                ^
```

I also got issues (although different from what you describe) with this url value. After removing the duplicate dot, it worked again. Could you try this?

Regarding picking list for geo: I hear you. While doing my changes, I noticed that @TomekMelissa seems to have started adding support for this, see https://github.com/microsoft/2LCS/blob/4914fbd91d25cc432378a818ab056b74cfe8d2f7/2LCS/Enumerations.cs#L54
Would love to make this more user friendly, but that will take some time.

**Comment by FH-Inway** [comment]
> If you like I can invite you to a project so you have some were to test

That would be awesome, thank you!

**Comment by FH-Inway** [comment]
@flauest This is now part of version [0.41.0](https://github.com/microsoft/2LCS/releases/tag/v.0.41.0).

@TomekMelissa I took the liberty of merging #76 and creating a new version with release notes. If nothing comes up until next week, I suggest we remove the prerelease flag and make it the latest version.
