### ISSUE TITLE
Can't get a list of packages for MS-hosted environments

### ISSUE THREAD

**Issue by CHJanusz** [microsoft/2LCS#89]
With the current implementation of HttpClientHelper.GetPagedDeployablePackageListUrl when trying to get a list of deployable packages for MS-hosted environment the list is empty. It looks like the reason is URL returned by this method. For CHE it works fine as {LcsUrl}/Environment/GetPagedDeployablePackageList[...] returns the list, but for MS-hosted env the list is empty. When in turn you use {LcsUrl}/EnvironmentServicingV2/GetPagedDeployablePackageList[...] it returns packages for MS-hosted env, but not for a CHE. 
It seems that if MS will not make EnvironmentServicingV2 return the list for both types of environments HttpClientHelper.GetPagedDeployablePackageListUrl method should return a different URL according to environment type.

**Comment by FH-Inway** [comment]
Thanks for reporting. I will take a look. If you feel up to it, let me know if you are interested in working on this. It seems you already found the locations in the code that need to be changed.

**Comment by CHJanusz** [comment]
Sure, I've craeted a pull request :)

**Comment by FH-Inway** [comment]
And merged #90 
Thanks a lot for the contribution, I will do a new release later this weekend.

**Comment by FH-Inway** [comment]
[Release v.0.48.0](https://github.com/microsoft/2LCS/releases/tag/v.0.48.0) is out!
Thanks again.
