### ISSUE TITLE
Optionally Prepopulate IP Address when adding Firewall Exception

### ISSUE THREAD

**Issue by tnoor-kr** [microsoft/2LCS#97]
It would be a productivity boost to prepopulate one's public IP when adding a firewall exception. We could make a call to a free service like `https://icanhazip.com` and use that to prepopulate the input or add as a suggestion below it. This could be exposed under the parameters as optional along with the option to configure the URL if the user prefers a different service.

If you're open to this idea, I'd be happy to do a PR on it.

![ms-teams-20240716-000045](https://github.com/user-attachments/assets/45790339-3b88-4e59-a8d3-efcd70f177ca)

**Comment by FH-Inway** [comment]
Hi, welcome to the repo and thanks for the suggestion. Sure, sounds like fun, let's do it 👍

**Comment by FH-Inway** [comment]
@milnet92 Thanks for the pr (the 100th btw. 🎉 ), looking good, this is now available in version [0.52.0](https://github.com/microsoft/2LCS/releases/tag/v.0.52.0)

@tnoor-kr Let us know if this works for you.

**Comment by tnoor-kr** [comment]
Thank you for getting to this sooner than I could have. I just tried it out and it populated the IP instantly.
