### ISSUE TITLE
Export users fails where a value is specified in AlternateEmails, resulting in "Please login to LCS again. Your cookie probably expired." error.

### ISSUE THREAD

**Issue by bn-cap-01** [microsoft/2LCS#98]
An exception is thrown on the JSON deserialise, and is caught in the generic exception handling.

The exception is: Error converting value to type 'System.Collections.Generic.List`1[System.String]'. Path 'Results[5].UserProfile.AlternateEmails'

**Comment by FH-Inway** [comment]
Welcome to the repo and thanks for taking the time to register with GitHub to report this issue AND providing a fix as well. That's awesome! :heart:
I noticed the issue as well some time ago, but when I tried to repro it, I could not find a project where it occurs. Found one today though, so I was able to verify the fix works on my side as well.
Released in new version [0.51.0](https://github.com/microsoft/2LCS/releases/tag/v.0.51.0) :rocket:
